export const urls = {
  Students: "/admin/students",
  StudentsPaginated: "/admin/students/paginated",
  StudentsRestore: "/admin/students/restore",
  Years: "/admin/years",
  YearsPaginated: "/admin/years/paginated",
  Teacher: "/admin/teachers",
  TeacherPaginated: "/admin/teachers/paginated",
  TeacherRestore: "/admin/teachers/restore",
  Course: "/admin/courses",
  CoursePaginated: "/admin/courses/paginated",
  Subject: "/admin/subjects",
  SubjectTeacher: "/admin/subjects/teacher",
  SubjectStudent: "/admin/students/subjects",
  SubjectPaginated: "admin/subjects/paginated",
  statistics: "/statistics/home/admin",
};
